name: Deploy Preview

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled]
    # branches:    
    #   - 'feature/**'

jobs:
  deploy-preview:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: GitHub Refs
        uses: rlespinasse/github-slug-action@v2.x

      - name: Test
        run: echo Running Tests!

      - name: Deploy
        if: github.event.label.name == 'deploy'
        run: echo Doing Deploy!

      # - name: Use Node.js
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: 14.x

      # - name: install dependencies
      #   run: npm install

      # - name: lint
      #   run: npm run lint

      # Note: the deploy can also use the secrets directly from the enviroment
      # so the configure-aws-credentials action isn't required, but it may
      # give us more flexability going forward
      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-east-1

      # - name: Serverless Deploy
      #   id: serverless_deploy
      #   if: github.event.label.name == 'deploy'
      #   run: npm run deploy